---
title: "Predicting Housing Prices with XGBoost Methodology"
subtitle: "Capstone Projects for Data Science - Spring 2026"
author: "Douglas Bogan and Susanna Brown (Advisor: Dr. Cohen)"
course: Capstone Projects in Data Science
date: '`r Sys.Date()`'
engine: knitr
format: 
  revealjs:
    smaller: true
    scrollable: true
    theme: sky
bibliography: references.bib
self-contained: true
execute: 
  warning: false
  message: false
---

## Introduction

-   Develop a storyline that captures attention and maintains interest.

-   Your audience is your peers

-   Clearly state the problem or question you're addressing.

-   Introduce why it is relevant needs.

-   Provide an overview of your approach.

## Methods

-   Detail the models or algorithms used.

-   Justify your choices based on the problem and data.

## Data Exploration and Visualization

-   Describe your data sources and collection process.

-   Present initial findings and insights through visualizations.

-   Highlight unexpected patterns or anomalies.

## Modeling and Results

-   Explain your data preprocessing and cleaning steps.

-   Present your key findings in a clear and concise manner.

-   Use visuals to support your claims.

-   **Tell a story about what the data reveals.**

## Conclusion

-   Summarize your key findings.

-   Discuss the implications of your results.

## References

```{=html}
<style type="text/css">
  #refs {
    font-size: 5px;
}
</style>
```

::: {#refs}
:::
